defaults:
  run:
    shell: bash -leo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python: ["3.9", "3.13"]
        include:
          - os: macos-latest
            python: "3.9"
          - os: windows-latest
            python: "3.9"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      PYTHON_VERSION: ${{ matrix.python }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python }}-pip-${{ hashFiles('./pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python }}-pip
      - name: Install PyTorch nightly
        run: |
          pip install --upgrade uv
          uv pip install --system --upgrade --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu
      - name: Install package
        run: |
          uv pip install -e '.[tests]'
      - name: Run tests
        run: pytest

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: # This configuration does not affect the page_build event above
      - created
