defaults:
  run:
    shell: bash -leo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python: ["3.9", "3.13"]
        include:
          - os: macos-latest
            python: "3.9"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      PYTHON_VERSION: ${{ matrix.python }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python }}
          activate-environment: true
          enable-cache: true
      - name: Install package
        run: uv pip install -e '.[test]' && uv lock
      - name: Run tests
        run: uv run --frozen pytest -n auto

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: # This configuration does not affect the page_build event above
      - created
